<a href="https://colab.research.google.com/github/teias-courses/dl99/blob/gh-pages/resources/colab_numpy_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Python Notebook, Google Colab 

Read More:
* [Jupyter Documentation](https://jupyter.org/documentation)
* [Overview of Colaboratory Features](https://colab.research.google.com/notebooks/basic_features_overview.ipynb)

## Python Notebook

A python notebook is a document consisting of two types of blocks (cells):
* **Code cell**: Python code (and its output)
* **Markdown Cell**: Text in markdown syntax (like this one)

When backed by a python kernel, we can run code cells and generate outputs...

Python notebooks are stored as ```.ipynb``` files.

### Code Cells

In [ ]:
x = 25
print(x)

x * 5   # prints value of last line as a expression

25


125

In [ ]:
y = x + 1   # has access to x which was defined above
y

26

We can run **Bash Commands** in code cells


In [ ]:
!wget -O hinton.jpg https://awards.acm.org/binaries/content/gallery/acm/awards/photo/h-j/hinton_4791679 

--2020-11-10 13:22:00--  https://awards.acm.org/binaries/content/gallery/acm/awards/photo/h-j/hinton_4791679
Resolving awards.acm.org (awards.acm.org)... 5.79.89.115, 5.79.89.114, 2001:1af8:4700:a158:121:0:1:114, ...
Connecting to awards.acm.org (awards.acm.org)|5.79.89.115|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 183274 (179K) [image/jpeg]
Saving to: ‘hinton.jpg’

hinton.jpg          100%[===================>] 178.98K   783KB/s    in 0.2s    

2020-11-10 13:22:01 (783 KB/s) - ‘hinton.jpg’ saved [183274/183274]



In [ ]:
data_dir = 'my_data'
!mkdir {data_dir}     # makes my_data directory
!ls

drive  hinton.jpg  my_data  sample_data


In [ ]:
!pwd
!cd my_data   # has no effect
!pwd

/content
/content


### Magic Commands

A very handy feature of IPython. There are two types of magic:
* **Line Magic** runs like a line of code.
* **Cell Magic** affects the behavior of the whole cell.




In [ ]:
%cd my_data
a = %pwd

/content/my_data


In [ ]:
%lsmagic

Available line magics:
%alias  %alias_magic  %autocall  %automagic  %autosave  %bookmark  %cat  %cd  %clear  %colors  %config  %connect_info  %cp  %debug  %dhist  %dirs  %doctest_mode  %ed  %edit  %env  %gui  %hist  %history  %killbgscripts  %ldir  %less  %lf  %lk  %ll  %load  %load_ext  %loadpy  %logoff  %logon  %logstart  %logstate  %logstop  %ls  %lsmagic  %lx  %macro  %magic  %man  %matplotlib  %mkdir  %more  %mv  %notebook  %page  %pastebin  %pdb  %pdef  %pdoc  %pfile  %pinfo  %pinfo2  %pip  %popd  %pprint  %precision  %profile  %prun  %psearch  %psource  %pushd  %pwd  %pycat  %pylab  %qtconsole  %quickref  %recall  %rehashx  %reload_ext  %rep  %rerun  %reset  %reset_selective  %rm  %rmdir  %run  %save  %sc  %set_env  %shell  %store  %sx  %system  %tb  %tensorflow_version  %time  %timeit  %unalias  %unload_ext  %who  %who_ls  %whos  %xdel  %xmode

Available cell magics:
%%!  %%HTML  %%SVG  %%bash  %%bigquery  %%capture  %%debug  %%file  %%html  %%javascript  %%js  %%latex  %%perl 

In [ ]:
%whos int

Variable   Type    Data/Info
----------------------------
x          int     25
y          int     26


In [ ]:
%timeit [i**2 for i in range(10**6)]

1 loop, best of 3: 268 ms per loop


In [ ]:
%pdb on
x = 1
y = x - 1
z = x/y
w = x + 1

Automatic pdb calling has been turned ON


ZeroDivisionError: ignored

> <ipython-input-10-2f9f57b0354d>(4)<module>()
      1 get_ipython().magic('pdb on')
      2 x = 1
      3 y = x - 1
----> 4 z = x/y
      5 w = x + 1

ipdb> q


In [ ]:
%pdb off

Automatic pdb calling has been turned OFF


#### Cell Magic

In [ ]:
%%time
l = [i**2 for i in range(10**7)]

CPU times: user 2.54 s, sys: 183 ms, total: 2.73 s
Wall time: 2.76 s


In [ ]:
%%html
This cell is <span style="background:#ddee66">rendered</span> as {x} html.
A <a href=""> link</a> to nowhere! 

In [ ]:
%%writefile -a test.txt
x = 5
i am "a student"

Writing test.txt


### Markdown Cells

This is a markdown cell.
It supports **bold**, *italicized* text formatting.

```
# And This is formatted as code
x = -13
y = abs(x * 5)
```





You can have lists...

* bulleted items
* more items

or 
1. numbered items
2. item 2

## Google Colab

Colab provides us python kernels hosted by Google and a user-friendly UI to work with our notebook.

* Almost all needed libraries for machine learning and deep learning are pre-installed in colab.
* We can use hardware accelarators (GPU, TPU) which is neccessary for model training.

In [ ]:
!nvidia-smi

Tue Nov 10 13:22:30 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 455.32.00    Driver Version: 418.67       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   61C    P8    11W /  70W |      0MiB / 15079MiB |      0%      Default |
|                               |                      |                 ERR! |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

### Google Drive Integration

In [ ]:
from google.colab import drive
drive.mount('drive')

### Colab Limitations
* We may loose your session by closing browser tab for a while
* Each session has a maximum runtime limit of 12H or less!
* You cannot have GPU/TPU runtimes whenever you want... Use GPU only when you need it.

### Use Shortcuts
* **Ctrl + Enter** runs curent cell
* **Shift + Enter** runs curent cell and moves to next or creates new cell
* ...

# Numpy

Used resources:
* [Official numpy Docs: Indexing](https://numpy.org/doc/stable/reference/arrays.indexing.html)
* [Numerical calculations with NumPy](http://kestrel.nmt.edu/~raymond/software/python_notes/paper003.html)
* [Introduction to Numpy and Pandas](https://github.com/guiwitz/NumpyPandas_course)

Provides an efficient way to do calculations on multi-dimensional numerical data.

* Its core data type is called **ndarray** or n-dimensional array. We will refer to ndarrays as arrays.

In [ ]:
import numpy as np  # everyone imports numpy like this

## Creating Arrays

### From Python List

In [ ]:
a = np.array([1, 3, 5, 2, 4, 6])
a

array([1, 3, 5, 2, 4, 6])

In [ ]:
b = np.array([[1., 3, 5], [2, 4, 6]])    # nested list
b

array([[1., 3., 5.],
       [2., 4., 6.]])

In [ ]:
c = np.array([[1, 3, 5], [2, 4, 6], [7, 9]])
c

array([list([1, 3, 5]), list([2, 4, 6]), list([7, 9])], dtype=object)

In [ ]:
print('a.dtype:', a.dtype, '\nb.dtype:', b.dtype)

a.dtype: int64 
b.dtype: float64


In [ ]:
print(b.astype(np.int64))   # or astype('int64')

[[1 3 5]
 [2 4 6]]


In [ ]:
print('a.ndim:', a.ndim, '\tb.ndim', b.ndim)      # number of dimensions
print('a.shape:', a.shape, '\tb.shape:', b.shape) # size of each dimension
print('a.size:', a.size, '\tb.size:', b.size)     # total size of array (number of items)

a.ndim: 1 	b.ndim 2
a.shape: (6,) 	b.shape: (2, 3)
a.size: 6 	b.size: 6


In [ ]:
%whos ndarray

Variable   Type       Data/Info
-------------------------------
a          ndarray    6: 6 elems, type `int64`, 48 bytes
b          ndarray    2x3: 6 elems, type `float64`, 48 bytes
c          ndarray    3: 3 elems, type `object`, 24 bytes


### 1D Sequences

In [ ]:
ar = np.arange(5)
ar

array([0, 1, 2, 3, 4])

In [ ]:
ar = np.arange(-5, 5)   # includes -5, excludes 5
ar

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4])

In [ ]:
ar = np.arange(-5, 5, 0.5)    # start, stop, step
ar

array([-5. , -4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,
        0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [ ]:
ln = np.linspace(-5, 5, 20)
ln

array([-5.        , -4.47368421, -3.94736842, -3.42105263, -2.89473684,
       -2.36842105, -1.84210526, -1.31578947, -0.78947368, -0.26315789,
        0.26315789,  0.78947368,  1.31578947,  1.84210526,  2.36842105,
        2.89473684,  3.42105263,  3.94736842,  4.47368421,  5.        ])

In [ ]:
%whos ndarray

Variable   Type       Data/Info
-------------------------------
a          ndarray    6: 6 elems, type `int64`, 48 bytes
ar         ndarray    20: 20 elems, type `float64`, 160 bytes
b          ndarray    2x3: 6 elems, type `float64`, 48 bytes
c          ndarray    3: 3 elems, type `object`, 24 bytes
ln         ndarray    20: 20 elems, type `float64`, 160 bytes


### Zeros & Ones

In [ ]:
z = np.zeros((2, 3, 5))
z

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [ ]:
o = np.ones((2, 3, 4, 2))
o

array([[[[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]]],


       [[[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]]]])

In [ ]:
e = np.empty((10, ))
e

array([3.2286668e-316, 0.0000000e+000, 0.0000000e+000, 0.0000000e+000,
       0.0000000e+000, 0.0000000e+000, 0.0000000e+000, 0.0000000e+000,
       0.0000000e+000, 0.0000000e+000])

### Random values

In [ ]:
rn = np.random.randint(0, 10, (3, 4))   # low, high, size(shape)
rn

array([[6, 5, 6, 6],
       [1, 7, 5, 8],
       [6, 3, 9, 5]])

In [ ]:
rn = np.random.rand(3, 4)
rn

array([[0.50686831, 0.09076964, 0.92103499, 0.29305406],
       [0.04924242, 0.66996767, 0.3009527 , 0.6344106 ],
       [0.57779368, 0.52594848, 0.91709998, 0.48573592]])

In [ ]:
nm = np.random.normal(1.0, 5.0, size=1000)
nm, nm.mean(), nm.std()

(array([ 1.19461992e+01,  3.59241961e+00,  1.99352748e+00, -1.71349872e+00,
        -4.71754592e+00,  5.46744247e+00, -7.98389488e+00,  2.69409351e+00,
         1.90841710e-01,  4.46807963e+00,  3.47547053e+00, -2.72161012e-01,
         5.25328391e+00, -5.12610461e+00,  8.63601987e-01, -3.29707051e+00,
         9.23341933e+00,  1.80220867e+00,  1.08557215e+01, -3.12999968e-01,
         6.82700603e+00, -3.70479274e+00,  2.77267100e+00, -8.64091624e+00,
        -3.21894199e+00,  3.98141470e+00, -1.78442259e+00, -1.69326245e+00,
         6.45035166e+00,  1.30063614e+00, -3.71967837e+00,  6.47784310e+00,
         4.93322461e+00,  3.31226139e+00,  4.26386096e+00, -4.54256133e-01,
        -8.60995929e-01,  6.95802694e-01, -1.95763948e+00,  1.41395451e+00,
        -2.37709342e+00,  2.56751522e+00,  6.52085743e+00, -3.12204936e-01,
         1.25639579e+00,  2.35984026e+00,  2.26893528e-01,  2.58402230e+00,
        -2.18328228e+00, -1.04191055e+01, -8.07454455e+00, -4.73835472e+00,
         4.3


## Accessing & Indexing Arrays

### Basic Indexing, Slicing

From numpy docs:
* Basic slicing extends Python’s basic concept of slicing to N dimensions.
* Basic slicing occurs when obj is a **slice object** (constructed by start:stop:step notation inside of brackets), an **integer**, or a **tuple of slice objects and integers**. Ellipsis and newaxis objects can be interspersed with these as well.

In [ ]:
a = np.array([1, 3, 5, 2, 4, 6])
a[2], a[2:5], a[:2]

(5, array([5, 2, 4]), array([1, 3]))

In [ ]:
b = np.array([[1, 3, 5], 
              [2, 4, 6]])
b[1], b[:1], b[1:]

(array([2, 4, 6]), array([[1, 3, 5]]), array([[2, 4, 6]]))

In [ ]:
b[-1, 2], b[0, :2]    # [ax0, ax1, ...]

(6, array([1, 3]))

In [ ]:
nm = np.random.normal(size=10)
print(nm)
nm[0:8:2]    # [start:stop:step, ]

[-0.08150409  0.4024019   0.08858401  0.11278456 -0.43865788 -0.20996886
  0.22493608  1.05259873 -0.4198612  -0.02351037]


array([-0.08150409,  0.08858401, -0.43865788,  0.22493608])

### Advanced Indexing

Again from numpy docs:

* Advanced indexing is triggered when the selection object, *obj*, is a **non-tuple sequence** object, an **ndarray** (of data type integer or bool), or a **tuple with at least one sequence object or ndarray** (of data type integer or bool). 
* There are two types of advanced indexing: **integer** and **Boolean**.

In [ ]:
a = np.array([1, 3, 5, 2, 4, 6])
a[[3, 5, 0]]    # non-tuple sequence, a[(3, 5, 0)] returns error! why?

array([2, 6, 1])

In [ ]:
print(nm)
print(a)
nm[a]   # indexing with another ndarray

[-0.08150409  0.4024019   0.08858401  0.11278456 -0.43865788 -0.20996886
  0.22493608  1.05259873 -0.4198612  -0.02351037]
[1 3 5 2 4 6]


array([ 0.4024019 ,  0.11278456, -0.20996886,  0.08858401, -0.43865788,
        0.22493608])

In [ ]:
b = np.array([[1, 3, 5], 
              [2, 4, 6]])
b[[1, 0, 1], [0, 2, 1]]   # tuple of sequence objects

array([2, 5, 4])

In [ ]:
print(b > 2)
b[b>2]    # boolean indexing

[[False  True  True]
 [False  True  True]]


array([3, 5, 4, 6])

### Views & Copies

It is very important to know what you get by indexing an array?
* a view of original array?
* or a copy of it?

In [ ]:
a = np.array([1, 3, 5, 2, 4, 6])
x = a[:4]
x

array([1, 3, 5, 2])

In [ ]:
a[2] = -100
x     # x was a view of a

array([   1,    3, -100,    2])

In [ ]:
a = np.array([1, 3, 5, 2, 4, 6])
x = a[[3, 0, 2]]
x

array([2, 1, 5])

In [ ]:
a[2] = -100
x     # x was a copy of a

array([2, 1, 5])

#### Remember
* What you get by **basic indexing** is a **view** of the original array.
* But **advanced indexing** returns a **copy** of it.

### Reshaping Arrays

We can change the number of array dimensions and the size of each dimension as long as the total number of array elements remains the same.

In [ ]:
b = np.array([[1., 3, 5], [2, 4, 6]])
b.shape

(2, 3)

In [ ]:
print('6:\t', b.reshape(6))   
print('(6,):\t', b.reshape((6,)))   
print('(1, 6):\t', b.reshape((1, 6)))
print('\n(6, 1):\n', b.reshape((6, 1)))

6:	 [1. 3. 5. 2. 4. 6.]
(6,):	 [1. 3. 5. 2. 4. 6.]
(1, 6):	 [[1. 3. 5. 2. 4. 6.]]

(6, 1):
 [[1.]
 [3.]
 [5.]
 [2.]
 [4.]
 [6.]]


In [ ]:
b.reshape((3, 4))

ValueError: ignored

In [ ]:
b.reshape((-1, 2))    # we dont know/care about axis-0

array([[1., 3.],
       [5., 2.],
       [4., 6.]])

## Array Mathematics

### Basic math

In [ ]:
x = np.array([[1., 2, 3],
              [4, 5, 6]])
y = np.array([[3., -1, -2],
              [4, 7, 0]])
print(x.shape, y.shape)

(2, 3) (2, 3)


In [ ]:
x + y

array([[ 4.,  1.,  1.],
       [ 8., 12.,  6.]])

In [ ]:
x * y     

array([[ 3., -2., -6.],
       [16., 35.,  0.]])

In [ ]:
x ** y

array([[1.00000000e+00, 5.00000000e-01, 1.11111111e-01],
       [2.56000000e+02, 7.81250000e+04, 1.00000000e+00]])

In [ ]:
x / y

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[ 0.33333333, -2.        , -1.5       ],
       [ 1.        ,  0.71428571,         inf]])

In [ ]:
x[x > y]

array([2., 3., 6.])

In [ ]:
x == y

array([[False, False, False],
       [ True, False, False]])

### Arrays with different shape
Numpy operations are usually done on pairs of arrays on an element-by-element basis. In the simplest case, the two arrays must have exactly the same shape, as in the above examples.

Numpy’s **broadcasting** rule relaxes this constraint when the arrays’ shapes meet certain constraints.

Read more on [numpy docs](https://numpy.org/doc/stable/user/basics.broadcasting.html).

In [ ]:
x + 10      # simplest form of broadcasting

array([[11., 12., 13.],
       [14., 15., 16.]])

In [ ]:
x + np.array([1, 2, 3])

array([[2., 4., 6.],
       [5., 7., 9.]])

In [ ]:
x + np.array([1, 2, 3, 4, 5])

ValueError: ignored

In [ ]:
x + np.array([1, 2])

ValueError: ignored

Two dimensions are compatible when
* they are equal, or
* one of them is 1

Also Arrays do not need to have the same number of dimensions. Lining up the sizes of the **trailing axes** of these arrays according to the broadcast rules, shows that they are compatible...

```
A      (2d array):  5 x 4
B      (1d array):      1
Result (2d array):  5 x 4

Image  (3d array): 256 x 256 x 3
Scale  (1d array):             3
Result (3d array): 256 x 256 x 3

A      (4d array):  8 x 1 x 6 x 1
B      (3d array):      7 x 1 x 9
Result          ???
```

In [ ]:
x = np.array([[1., 2, 3],
              [4, 5, 6]])
y = np.array([[3., -1, -2],
              [5, 7, 0]])
y1 = y[1]
y2 = y[:, 2]
print(x.shape, y.shape)
print(y1.shape, y2.shape)

(2, 3) (2, 3)
(3,) (2,)


In [ ]:
x + y1

array([[ 6.,  9.,  3.],
       [ 9., 12.,  6.]])

In [ ]:
x + y2

ValueError: ignored

In [ ]:
x + y2.reshape(2, 1)    

array([[-1.,  0.,  1.],
       [ 4.,  5.,  6.]])

### Array assignment

In [ ]:
x = np.ones((3, 4))
x

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
x[0] = 3
x

array([[3., 3., 3., 3.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
x[2] = np.zeros((4,))
x

array([[3., 3., 3., 3.],
       [1., 1., 1., 1.],
       [0., 0., 0., 0.]])

In [ ]:
x[[0, 1], [1, 2]] = -np.ones((2,))    # advanced indexing
x

array([[ 3., -1.,  3.,  3.],
       [ 1.,  1., -1.,  1.],
       [ 0.,  0.,  0.,  0.]])

### Array methods

In [ ]:
a = np.array([[1., 5, 3],
              [4, 2, 6]])

In [ ]:
a.max(), a.min()

(6.0, 1.0)

In [ ]:
a.sum(), a.mean()

(21.0, 3.5)

In [ ]:
a.var(), a.std()

(2.9166666666666665, 1.707825127659933)

In [ ]:
a.max(axis=1), a.sum(axis=0)

(array([5., 6.]), array([5., 7., 9.]))

In [ ]:
a.transpose()   # a.T

array([[1., 4.],
       [5., 2.],
       [3., 6.]])

In [ ]:
a.reshape((3, 2))

array([[1., 5.],
       [3., 4.],
       [2., 6.]])

## Combining Arrays

### Concatenation

Extends arrays along specified axis to get a larger array, with same number of dimensions.

In [ ]:
a = np.ones((3, 4))
b = 2 * np.ones((3, 5))
c = 3 * np.ones((3, 4))
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.concatenate([a, c])          # default axis is 0

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.]])

In [ ]:
np.concatenate([a, b])          # default axis is 0

ValueError: ignored

In [ ]:
np.concatenate([a, b], axis=1)    # or axis=-1

array([[1., 1., 1., 1., 2., 2., 2., 2., 2.],
       [1., 1., 1., 1., 2., 2., 2., 2., 2.],
       [1., 1., 1., 1., 2., 2., 2., 2., 2.]])

### Stacking

If we have several arrays with **exact same sizes**, we can also stack them, i.e. assemble them along a new dimension.

In [ ]:
stack = np.stack([a, c])    # adds new axis in 0
print(stack.shape)
stack

(2, 3, 4)


array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]])

In [ ]:
stack = np.stack([a, c], axis=-1)
print(stack.shape)
stack

(3, 4, 2)


array([[[1., 3.],
        [1., 3.],
        [1., 3.],
        [1., 3.]],

       [[1., 3.],
        [1., 3.],
        [1., 3.],
        [1., 3.]],

       [[1., 3.],
        [1., 3.],
        [1., 3.],
        [1., 3.]]])

## Save & Load Arrays

Search for it when needed! :)